Fix Stack overflow for large clusters
fulcrumgenomics/fgsv pull request #18
Opened 2022-08-16 04:54 UTC by nh13

I'd rather have `extractClusterFor` be tail recursive or in a loop, but I couldn't figure out how to do that easily, so this will do.

2022-08-16 04:54 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileup.scala
> +    val neighbors: PileupGroup = pileupToNeighbors.getOrElse(pileup, IndexedSeq()).filter(neighborsToIgnore.contains)
this needs careful thought on correctness

2022-08-16 19:10 UTC, pamelarussell requested changes

2022-08-16 19:10 UTC, pamelarussell commented on src/main/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileup.scala
> +   * @parma neighborsToIgnore Set of pileups to ignore, as they are being considered in parent calls to this method
```suggestion
   * @param neighborsToIgnore Set of pileups to ignore, as they are being considered in parent calls to this method
```

2022-08-16 19:10 UTC, pamelarussell commented on src/main/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileup.scala
> +    val neighbors: PileupGroup = pileupToNeighbors.getOrElse(pileup, IndexedSeq()).filter(neighborsToIgnore.contains)
@nh13 are you able to generate an example that causes a stack overflow and add it as a test case?

At a minimum, we should fix the compile errors in the [test file](https://github.com/fulcrumgenomics/fgsv/blob/main/src/test/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileupTest.scala) and make sure we haven't broken any known cases.

2022-09-14 17:43 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileup.scala
> +  def toClusters(pileupToNeighbors: Map[BreakpointPileup, PileupGroup]): Seq[PileupGroup] = {
Could not add a test case that made the previous implementation overflow due to restrictions on sharing that data.  Not sure it's worth it, but happy to add a few more test cases if you think that would be worth it.

2022-09-14 17:44 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileup.scala
> +        remaining += rootPileup
```suggestion
        remaining.enqueue(rootPileup)
```

2022-09-14 17:46 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileup.scala
> +            remaining ++= pileupToNeighbors(curPileup).filterNot(visited.contains)
I wonder if we can avoid enqueueing the same pileup multiple times if we mark it as visited after we've enqueued it, then remove if on line 175.
```suggestion
            val unvisited = pileupToNeighbors(curPileup).filterNot(visited.contains)
            remaining ++= unvisited
            unvisited.foreach(visited.add)
```

2022-09-14 17:49 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileup.scala
> +          unvisited.foreach(visited.add)
```suggestion
          visited ++= unvisited
```

2022-09-14 22:09 UTC, pamelarussell requested changes

2022-09-14 22:09 UTC, pamelarussell commented on src/test/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileupTest.scala
> -  "AggregateSvPileup.extractClusterFor" should "return correct cluster of size 1" in {
Why remove these two tests?

2022-09-14 22:40 UTC, nh13 commented on src/test/scala/com/fulcrumgenomics/sv/tools/AggregateSvPileupTest.scala
> -  "AggregateSvPileup.extractClusterFor" should "return correct cluster of size 1" in {
The method no longer exists.

2022-09-14 22:45 UTC, pamelarussell approved these changes

2022-09-15 16:59 UTC, merged